### PR TITLE
msg.precision  for v1.8 and 2.0

### PR DESCRIPTION
**Pull request by vdwpsmt**
https://github.com/mblackstock/node-red-contrib-influxdb/issues/123

### CODE REVIEW

**Comment by vdwpsmt** [comment]
@mblackstock  kind reminder.  Is it possible to review this possible bug and according revision?

**Comment by mblackstock** [comment]
Apologies for the delay.  Thank you for this.

This looks pretty simple, but it would be good to update the documentation in the output and batch nodes to reflect that this feature is supported in both versions now.  A simple test flow that demonstrates the change would be helpful too.

**Comment by vdwpsmt** [comment]
@mblackstock ok, on updating and testing I realized that the modification will not work the way I wrote it.  I'm not a specialist and not sure how to solve this.  The problem:

on influx version_1x the precision is added as an argument to the write method.
on influx version_18_flux and version_20 the precision is added as an argument on creating the write client, so before any message has arrived.  
I don't know how to update the write precision on an existing client instance.  And I don't suppose it's good practice to create a write client on every incoming message?

**Comment by vdwpsmt** [comment]
I checked some more things.  I suspect it would be possible to change the precision by modifying the path.
That's what's stated here:  https://influxdata.github.io/influxdb-client-js/influxdb-client.writeapi.path.html
I did a short test and this seems to work.  So I suppose it would be possible to change the path on every incoming message.  (Better would be to change it conditionally, if precision has changed compared to previous message).  
For now, I fear it's not important enough to spend more time on it.  So indeed, we'll keep it with this comment for now.

**Pull request closed without merging**
